'use strict';
const {data:d,kind,brand}=JSON.parse(document.querySelector('#payload').textContent);
let lang=d.language||'es',page=0,priorFocus=null,remaining=300,timer=null;
const ui={es:['Pausar animación','Reanudar animación','Proyectar','Imprimir','Anterior','Siguiente','completadas','Contexto','Ajustes','Copiar prompt','Copiado','No se pudo copiar; selecciona el texto','Completado ✓','Marcar completado','Notas de facilitación','Evidencia','Criterios de logro','Tiempo restante','Duración en minutos','Iniciar / pausar','Reiniciar','Revelar pregunta','Prompt completo','Ejemplo'],en:['Pause animation','Resume animation','Project','Print','Previous','Next','completed','Context','Settings','Copy prompt','Copied','Copy failed; select the text','Completed ✓','Mark completed','Facilitator notes','Evidence','Success criteria','Remaining time','Duration in minutes','Start / pause','Reset','Reveal question','Full prompt','Example'],pt:['Pausar animação','Retomar animação','Projetar','Imprimir','Anterior','Próximo','concluídas','Contexto','Configurações','Copiar prompt','Copiado','Não foi possível copiar; selecione o texto','Concluído ✓','Marcar concluído','Notas de facilitação','Evidência','Critérios de sucesso','Tempo restante','Duração em minutos','Iniciar / pausar','Reiniciar','Revelar pergunta','Prompt completo','Exemplo']};ui.fr=['Mettre en pause','Reprendre l’animation','Projeter','Imprimer','Précédent','Suivant','terminées','Contexte','Réglages','Copier le prompt','Copié','Copie impossible ; sélectionnez le texte','Terminé ✓','Marquer terminé','Notes de facilitation','Preuves','Critères de réussite','Temps restant','Durée en minutes','Démarrer / pause','Réinitialiser','Révéler la question','Prompt complet','Exemple'];const T=n=>(ui[lang]||ui.es)[n];
const key='frames-aula:'+location.pathname+':'+JSON.stringify(d.title),state=(()=>{try{return JSON.parse(localStorage.getItem(key))||{values:{},done:{}}}catch{return {values:{},done:{}}}})();
const save=()=>{try{localStorage.setItem(key,JSON.stringify(state))}catch{}};
const L=x=>typeof x==='object'&&x!==null?(x[lang]??x.es??Object.values(x)[0]??''):String(x??'');
const E=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e};
const main=document.querySelector('main');document.body.dataset.kind=kind;if(d._mobile)document.body.classList.add('mobile-edition');document.querySelector('#brand').textContent=brand.name;
const select=document.querySelector('#language');(d.languages||['es']).forEach(x=>{const o=E('option',x);o.value=x;select.append(o)});select.value=lang;select.onchange=()=>{lang=select.value;document.documentElement.lang=lang;render()};
function fields(s){return [...(s.fields||[]),...(s.settings||[]).map(f=>({...f,setting:true}))]}
function prompt(s){return L(s.prompt).replace(/\{\{(.*?)\}\}/g,(_,k)=>state.values[s.id+':'+k]??L(fields(s).find(f=>f.key===k)?.default??''))}
function scene(name){const NS='http://www.w3.org/2000/svg',svg=document.createElementNS(NS,'svg');svg.setAttribute('viewBox','0 0 600 180');svg.setAttribute('aria-hidden','true');svg.classList.add('scene');function shape(tag,attrs){const n=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));svg.append(n);return n}const accent=brand.colors.gold,ink=brand.colors.night;const mode=['flow','steps','orbit','gate','contrast'].includes(name)?name:'orbit';if(mode==='flow'){shape('path',{d:'M40 90 Q160 10 300 90 T560 90',fill:'none',stroke:ink,'stroke-width':5});for(let i=0;i<4;i++)shape('circle',{cx:80+i*140,cy:90,r:16,fill:accent})}if(mode==='steps'){for(let i=0;i<4;i++)shape('rect',{x:80+i*120,y:120-i*25,width:95,height:30+i*25,rx:8,fill:i%2?ink:accent})}if(mode==='orbit'){shape('ellipse',{cx:300,cy:90,rx:180,ry:65,fill:'none',stroke:ink,'stroke-width':3});shape('circle',{cx:300,cy:90,r:25,fill:ink});shape('circle',{cx:440,cy:90,r:17,fill:accent,class:'moving'})}if(mode==='gate'){shape('path',{d:'M150 155V30H450V155',fill:'none',stroke:ink,'stroke-width':10});shape('path',{d:'M220 95L275 140L390 45',fill:'none',stroke:accent,'stroke-width':12})}if(mode==='contrast'){shape('rect',{x:50,y:25,width:220,height:130,rx:16,fill:ink});shape('rect',{x:330,y:25,width:220,height:130,rx:16,fill:accent});shape('path',{d:'M285 90H315M305 80L315 90L305 100',fill:'none',stroke:ink,'stroke-width':4})}return svg}
function render(){main.replaceChildren();main.append(E('h1',L(d.title)));if(d.thesis){const thesis=E('aside',undefined,'thesis');thesis.append(E('h2',L(d.thesis.title||d.thesis)));(d.thesis.pillars||[]).forEach(p=>thesis.append(E('p',p.achieves?L(p.achieves)+' · '+L(p.proof):L(p))));main.append(thesis)}if(d.objectives?.length){const list=E('ul',undefined,'objectives');d.objectives.forEach(x=>list.append(E('li',L(x))));main.append(list)}
d.sections.forEach((s,i)=>{const section=E('section',undefined,'card');section.id=s.id;section.hidden=['immersive-class','masterclass','dynamic-commercial-decks'].includes(kind)&&i!==page;section.append(E('h2',L(s.title)));if(kind!=='lean-coffee')section.append(E('p',L(s.body)));if(s.scene)section.append(scene(s.scene));
if(fields(s).length){const context=E('fieldset');context.append(E('legend',T(7)));const settings=E('details');settings.append(E('summary',T(8)));fields(s).forEach(f=>{const label=E('label',L(f.label)),input=E('textarea');input.value=state.values[s.id+':'+f.key]??L(f.default??'');input.oninput=()=>{state.values[s.id+':'+f.key]=input.value;save();if(section.querySelector('pre'))section.querySelector('pre').textContent=prompt(s)};label.append(input);(f.setting?settings:context).append(label)});section.append(context);if(settings.children.length>1)section.append(settings)}
if(s.prompt){const disclosure=E('details');disclosure.open=kind==='workbook';disclosure.append(E('summary',T(22)),E('pre',prompt(s)));section.append(disclosure);const copy=E('button',T(9));copy.onclick=async()=>{const text=prompt(s);let success=false;try{await navigator.clipboard.writeText(text);success=true}catch{const t=E('textarea');t.value=text;section.append(t);t.select();try{success=document.execCommand('copy')}catch{}if(success)t.remove()}copy.textContent=T(success?10:11)};section.append(copy)}
if(s.exemplar){const ex=E('details');ex.append(E('summary',T(23)),E('p',L(s.exemplar)));section.append(ex)}
if(s.table){const table=E('table'),head=E('thead'),tr=E('tr');(s.table.headers||[]).forEach(x=>{const th=E('th',L(x));th.scope='col';tr.append(th)});head.append(tr);table.append(head);const body=E('tbody');(s.table.rows||[]).forEach(row=>{const line=E('tr');row.forEach(x=>line.append(E('td',L(x))));body.append(line)});table.append(body);section.append(table)}
(s.accordion||[]).forEach(item=>{const details=E('details');details.append(E('summary',L(item.title)),E('p',L(item.body)));section.append(details)});
if(s.tabs?.length){const tablist=E('div',undefined,'tablist');tablist.setAttribute('role','tablist');const panels=[];const buttons=[];s.tabs.forEach((item,n)=>{const button=E('button',L(item.title)),panel=E('div');button.id=s.id+'-tab-'+n;panel.id=s.id+'-panel-'+n;button.setAttribute('role','tab');button.setAttribute('aria-controls',panel.id);panel.setAttribute('role','tabpanel');panel.setAttribute('aria-labelledby',button.id);panel.textContent=L(item.body);panel.tabIndex=0;panel.hidden=n!==0;button.setAttribute('aria-selected',String(n===0));button.tabIndex=n===0?0:-1;buttons.push(button);panels.push(panel);button.onclick=()=>choose(n);button.onkeydown=e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();e.stopPropagation();const next=e.key==='Home'?0:e.key==='End'?buttons.length-1:(n+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;choose(next);buttons[next].focus()}};tablist.append(button)});function choose(n){buttons.forEach((b,i)=>{b.setAttribute('aria-selected',String(i===n));b.tabIndex=i===n?0:-1;panels[i].hidden=i!==n})}section.append(tablist,...panels)}
const done=E('button',T(state.done[s.id]?12:13));done.setAttribute('aria-pressed',String(!!state.done[s.id]));done.onclick=()=>{state.done[s.id]=!state.done[s.id];save();render()};section.append(done);if(kind==='workbook'){const projection=E('button',T(2));projection.onclick=()=>project(section);section.append(projection)}
(s.links||[]).forEach(link=>{const a=E('a',L(link.label),'piece');a.href=link.href;section.append(a)});
if(s.notes&&!new URLSearchParams(location.search).has('audience')){const notes=E('details',undefined,'notes');notes.append(E('summary',T(14)),E('p',L(s.notes)));section.append(notes)}main.append(section)});
if(d.facts?.length){const facts=E('details');facts.append(E('summary',T(15)));d.facts.forEach(f=>facts.append(E('p',L(f.text)+' · '+f.source+' · '+f.sha256)));main.append(facts)}
if(d.acceptance?.length){main.append(E('h2',T(16)));d.acceptance.forEach(x=>main.append(E('p',L(x))))}
if(d.pieces?.length){const links=E('div',undefined,'pieces');d.pieces.forEach(p=>{const a=E('a',p.kind,'piece');a.href=p.href;links.append(a)});main.append(links)}
if(kind==='lean-coffee'){const clock=E('output',format(),'timer');clock.id='timer';clock.setAttribute('aria-label',T(17));main.append(clock);const minutes=E('input');minutes.type='number';minutes.min=1;minutes.max=120;minutes.value=Math.ceil(remaining/60)||5;minutes.setAttribute('aria-label',T(18));minutes.onchange=()=>{if(!timer){remaining=Math.min(120,Math.max(1,Number(minutes.value)||5))*60;document.querySelector('#timer').textContent=format()}};main.append(minutes);const start=E('button',T(19));start.onclick=()=>{if(timer){clearInterval(timer);timer=null;return}timer=setInterval(()=>{remaining=Math.max(0,remaining-1);const node=document.querySelector('#timer');if(node)node.textContent=format();if(!remaining){clearInterval(timer);timer=null;node?.setAttribute('aria-live','assertive')}},1000)};const reset=E('button',T(20));reset.onclick=()=>{clearInterval(timer);timer=null;remaining=Math.min(120,Math.max(1,Number(minutes.value)||5))*60;document.querySelector('#timer').textContent=format()};const reveal=E('button',T(21));const question=E('p',L(d.sections[page].body));question.hidden=true;reveal.onclick=()=>question.hidden=!question.hidden;main.append(start,reset,reveal,question)}
document.querySelector('#position').textContent=`${page+1} / ${d.sections.length} · ${Object.values(state.done).filter(Boolean).length} ${T(6)}`;document.querySelector('#prev').textContent=T(4);document.querySelector('#next').textContent=T(5);document.querySelector('#prev').disabled=page===0;document.querySelector('#next').disabled=page===d.sections.length-1;document.querySelector('#motion').textContent=T(document.body.classList.contains('paused')?1:0);document.querySelector('#projection').textContent=T(2);document.querySelector('button[onclick]').textContent=T(3)}
function format(){return Math.floor(remaining/60)+':'+String(remaining%60).padStart(2,'0')}
function move(n){page=Math.max(0,Math.min(d.sections.length-1,page+n));render();history.replaceState(null,'','#'+d.sections[page].id);main.focus()}
document.querySelector('#prev').onclick=()=>move(-1);document.querySelector('#next').onclick=()=>move(1);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.body.classList.contains('projection')){project();return}if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(e.key==='ArrowRight')move(1);if(e.key==='ArrowLeft')move(-1);if(e.key==='Escape'&&document.body.classList.contains('projection'))project()});
const motion=document.querySelector('#motion');motion.onclick=()=>{const paused=document.body.classList.toggle('paused');motion.textContent=T(paused?1:0);motion.setAttribute('aria-pressed',String(paused))};
function project(card){if(document.body.classList.contains('projection')){document.body.classList.remove('projection');document.querySelector('.projected-card')?.classList.remove('projected-card');priorFocus?.focus()}else{priorFocus=document.activeElement;document.body.classList.add('projection');card?.classList.add('projected-card');(card||main).tabIndex=-1;(card||main).focus()}}document.querySelector('#projection').onclick=()=>project();const initial=d.sections.findIndex(s=>s.id===location.hash.slice(1));if(initial>=0)page=initial;render();
